### ISSUE TITLE
Error on entity dirty tracking

### ISSUE THREAD

**Issue by vyper** [hanami/model#217]
I got an unexpected "error" in my entity using dirty tracking. If I change the includes order in my entity the `changed?` and `changed_attributes` does not work perfectly.
# For this includes order

``` ruby
Lotus::Model::VERSION # => "0.4.1"

class Pet
  include Lotus::Entity
  include Lotus::Entity::DirtyTracking
  include Lotus::Validations

  attribute :name, type: String
end

pet = PetRepository.first
pet.changed?           # => false
pet.name = 'name'      # => "name"
pet.changed?           # => false
pet.changed_attributes # => {}
```
# Inverting Validations and DirtyTracking

``` ruby
class Pet
  include Lotus::Entity
  include Lotus::Validations
  include Lotus::Entity::DirtyTracking

  attribute :name, type: String
end

pet = PetRepository.first
pet.changed?           # => false
pet.name = 'name'      # => "name"
pet.changed?           # => true
pet.changed_attributes # => {:name=>"Bacon"}
```

**Comment by joneslee85** [comment]
@vyper can you please update the description with more details on what this ticket is about?

**Comment by AlfonsoUceda** [comment]
@joneslee85 if you see the order inclusion between `Lotus::Validations` and `Lotus::Entity::DirtyTracking` you'll see the problem

**Comment by vyper** [comment]
Sorry @joneslee85, I sent incompleted description. But, @AlfonsoUceda is right.

**Comment by mymai91** [comment]
@vyper Can you make it clarify? 
@joneslee85 I'm testing on lastest version Lotus model. I change order's `Lotus::Entity::DirtyTracking && Lotus::Validations`. It work okay with me.

**Comment by joneslee85** [comment]
@mymai91 that's right, as @vyper has described in the description, the ordering should not matter, the function should work in either ordering.

**Comment by mymai91** [comment]
@vyper Can you show me your code? I need to know more detail.

**Comment by joneslee85** [comment]
@vyper https://github.com/lotus/model/pull/238, My was trying to replicate the error but she could not

**Comment by joneslee85** [comment]
@mymai91 on second look, your test is not the same as the issue description, as you can see that @vyper was fetching the entity from the repository. Can you please update your PR to do it and see if it fails?

**Comment by mymai91** [comment]
@joneslee85 Got it. I will update.

**Comment by jodosha** [comment]
We should make it to work, because this is clearly a bug.

However, I'm observing a dangerous pattern here: try to reproduce AR models with Lotus::Model. There is a reason why we shipped decoupled modules and gems for these behaviors: separation of concerns between roles.

One cannot agree with this design, but if a dev needs everything to live in the same object, it's better to use AR instead.

**Comment by jodosha** [comment]
As of v0.7.0 we won't support _dirty tracking_ anymore. In the future we'll support [Changesets](https://hexdocs.pm/ecto/Ecto.Changeset.html) which are able to tell the attributes that changed.
