### ISSUE TITLE
Repository does not respect default values on persisted entities

### ISSUE THREAD

**Issue by taylorfinnell** [hanami/model#237]
When you define a default value in the migrator, the repository does not respect it.

```
Lotus::Model.migration do
  up do
    create_table :user_info do
      primary_key :id

      column :rank, Integer, default: -1
      ...
```

`ui = UserInfoRepository.create(UserInfo.new(version: 1))`

```
ui.rank
 => nil
```

**Comment by joneslee85** [comment]
@taylorfinnell thanks for the bug report, for our investigation, can you please also provide your mapper?

**Comment by taylorfinnell** [comment]
Mapping

```
collection :user_info do
  entity      Fastpeek::UserInfo
  repository  Fastpeek::UserInfoRepository

  attribute :id,   Integer
  attribute :rank, Integer
end
```

Using the SQL adapter. Here is a potential solution for the issue, originally used the schema for the defaults but @solnic showed me the Dataset#returning method :)

https://github.com/taylorfinnell/model/commit/52f7683d88308fb8db265d926194c8ebab90e5ef

**Comment by taylorfinnell** [comment]
Got a chance to run the tests. Looks like sqlite does not support RETURNING. So the commit in my previous comment is not a fully working solution
