### ISSUE TITLE
Path glob to mapper files

### ISSUE THREAD

**Issue by matheusca** [hanami/model#245]
Hi!

Organize my mapping files I separate mapping in many files that makes sense for me. So I created a main mapping file that it got all path, as following:

``` ruby
﻿Lotus::Model.configure do
  adapter type: :sql, ...

  mapping 'mapping/users'
  mapping 'mapping/tasks'
  mapping 'mapping/scheduled'
end
```

It works very well, but it more redundancy for each mapping I will need putting these files in main mapping file.

My suggestion if will be possible use a glob path in main file. For instance, my file could be more elegant as following:

``` ruby
﻿Lotus::Model.configure do
  adapter type: :sql, ...

  mapping 'mapping/*'
end
```

I saw that it is not possible at the moment, because the `Config::Model`(https://github.com/lotus/model/blob/master/lib/lotus/model/config/mapper.rb#L34) try get a realpath.

If guys agree with me, I will implement it refactoring the code.

**Comment by AlfonsoUceda** [comment]
I like the idea to separate in several files the mapping, because in big applications the mapping will be big.

what do you think @lotus/core-team ?

**Comment by joneslee85** [comment]
@AlfonsoUceda I do like this idea too, I even think that having `lib/bookshelf/mappers` as a conventional placeholder. Thoughts?

**Comment by AlfonsoUceda** [comment]
:+1:

**Comment by joneslee85** [comment]
On second look, doing multiple `mapping` does not work correctly in the current version, the latter one would override the one before that. So the PR should also handle that first.

**Comment by jodosha** [comment]
As of v0.7.0 we don't support global `mapping` anymore.
