### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by aderyabin** [hanami/model#257]
I want to create PR that add possibility to run test with specific adapter, for example
```
rake test:postgresql
```

Does it sense?

// cc @jodosha @joneslee85

**Comment by joneslee85** [comment]
@aderyabin can't we do it with UNIX variable instead?

**Comment by aderyabin** [comment]
yes, we can do it like in AR
```
ARCONN=mysql rake test
```

**Comment by joneslee85** [comment]
I like it, but wondering if it would brings the mutations of Travis CI matrix to unmanageable number

**Comment by jodosha** [comment]
> I like it, but wondering if it would brings the mutations of Travis CI matrix to unmanageable number

What if the default runs all the tests (like now), so we can use it with Travis CI, without growing the build matrix? I see this trick useful for dev mode. @aderyabin was this your intention?

**Comment by aderyabin** [comment]
I suggest only add option – run test with specific adapter, for example:
```
ADAPTER=postgres rake test
``` 
without changes in default task (test all adapters)
```
rake test
```

**Comment by jodosha** [comment]
@aderyabin :+1:

**Comment by joneslee85** [comment]
:+1:

**Comment by hlegius** [comment]
@aderyabin I was talking to @jodosha about to split tests into two groups: unit and integration. IMO, it will help to prevent 'too many open files' error in the future due lots of resources left behind without closing it properly (sometimes its too way complicated to close anyway). Also, may improve _our_ development process. This separation will be also reflected within Travis which will call explicitly unit and integration in this order of calling to avoid the first item mentioned above. @jodosha agreed (at the first time :P). What do you think, guys?

**Comment by pascalbetz** [comment]
i agree. but i don't have to manage the build matrix at travis:-)

but i disagree that this should be the fix to the "too many open files" problem. If this exists, then it's a problem with the tests allocating to many resources and should be fixed. Currently we assume that it's the tests which are causing these problems. But it might as well be the framework itself. Which would then go unnoticed.

**Comment by hlegius** [comment]
@pascalbetz hmm.. I've fixed the 'too many open files' issue days ago. it was merged into master one day later. My concern is about when new files get added into repository people forget to close connections properly (as it was the issue before) - that's why I suggested split within Travis as well.

**Comment by joneslee85** [comment]
generally I find this idea useful for dev mode. Furthermore I think I would make tests simpler and easier to track down bugs.

Please go ahead

**Comment by jodosha** [comment]
> generally I find this idea useful for dev mode.

yup, agreed. :+1:

**Comment by aderyabin** [comment]
Absolutely, all tests improvements for development usage only without changes in Travis integration.

**Comment by jodosha** [comment]
Closing this issue. Read more at: https://github.com/hanami/model/pull/312#issuecomment-210447550
