### ISSUE TITLE
Booleans can't be dumped in repository

### ISSUE THREAD

**Issue by SleeplessByte** [hanami/model#272]
```
undefined method `dump' for TrueClass:Class
```

Given the mapping

``` Ruby
collection :foos do
  entity     Foo
  repository FooRepository
  attribute :bar, TrueClass
end
```

And the creation

``` Ruby
@foo = Foo.new( params[ :foo ] ) #form_for :foo
FooRepository.create( @foo )
```

**Comment by jodosha** [comment]
@SleeplessByte Thanks again for reporting this. You should try with `Boolean` instead of `TrueClass` in your mapping. See https://github.com/lotus/model/blob/master/lib/lotus/model/mapping/coercers.rb#L43 for reference.

If there is some part of the documentation that reports `TrueClass` instead of `Boolean`, can you please point it to me, or open a PR with the fix? Thank you very much! :+1:

**Comment by SleeplessByte** [comment]
Yeah the reference is made to Sequel, but the changes are not pointed out.
In Sequel for Ruby there is no Boolean class.

I'll check the docs again :)

**Comment by SleeplessByte** [comment]
@jodosha the `TrueClass` type is never referenced in the documentation but neither is `Boolean`. I assumed `TrueClass` because of the last paragraph on [Migrations: Overview](http://lotusrb.org/guides/migrations/overview/).

I would suggest adding this to the documentation, as `Boolean` is not a stdlib type, same for `Array`.

**Comment by jodosha** [comment]
@SleeplessByte The problem with migrations is that the internal block is delegated to Sequel, which doesn't support `Boolean` but `TrueClass`/`FalseClass`.

`Array` isn't a stdlib type? It's core, but it's shipped with Ruby. What do you mean by that?

**Comment by SleeplessByte** [comment]
@jodosha I guess what I am saying is is it is really weird imo to use `Boolean` in one place and `TrueClass` in another place, and it's not documented anywhere.

**Comment by jodosha** [comment]
@SleeplessByte Oh okay :)

**Comment by jodosha** [comment]
@SleeplessByte 

> I guess what I am saying is is it is really weird imo to use `Boolean` in one place and `TrueClass` in another place

Good point, I'm reopening this. :+1:
