### ISSUE TITLE
Cannot log raw SQL

### ISSUE THREAD

**Issue by davidpelaez** [hanami/model#277]
Hi.

I tried finding a way to log the requests being sent to the server but I couldn't find anything related to that in the code. Is there a way to do this that I'm unaware of or this is not currently possible? I saw Sequel has an option but that would mean having direct access to the DB object and I see it's under a couple of layers in the code and I couldn't find a way to reach it simply (which of course seems logical by design).

Thanks

**Comment by jodosha** [comment]
@davidpelaez Hey, thanks for asking :+1: It's a missing feature that we want to address. :smile: For now it's not possible unless you fiddle with low level Sequel connection.

**Comment by davidpelaez** [comment]
Ok. Thanks for replying. Can we leave this opened and include it in a feature release?

**Comment by jodosha** [comment]
@davidpelaez Absolutely :+1: I'm gonna create a special GH label for this purpose.
