### ISSUE TITLE
Raise error when :id isn't defined in a mapping since it's required by the repositories

### ISSUE THREAD

**Issue by davidpelaez** [hanami/model#278]
If you set a custom field as primary key using the identity method in a collection mapping, the update action on the repository doesn't work because it checks explicitly for the id of the entity. It's defined here:

https://github.com/lotus/model/blob/9801dd781dc107aa0888430b220c0293d3eff258/lib/lotus/repository.rb#L830-L837

**Comment by davidpelaez** [comment]
I just checked some more and I found that you can make it work using something like `  attribute :id,    Integer, as: :_id`. I'm changing the issue title so that lotus should complain if the :id attribute isn't defined because it's required.

**Comment by jodosha** [comment]
@davidpelaez I understand the problem and how you solved it. What's not clear to me is where, when and how an exception should be raised and under which situation? Can you please clarify? Thank you! :smile:

**Comment by davidpelaez** [comment]
What I mean is that having an `id` attribute is required. So it could be nice to throw an error when a mapping doesn't contain an `id` attribute. Just a edge case of throwing errors to help the user know what she did wrong. In a way I refer to complaining because a requirement as not fulfilled.

**Comment by davidpelaez** [comment]
Is it clear? I'm glad to clarify if not. :)

**Comment by jodosha** [comment]
@davidpelaez Now, it's clear. Thank you :+1:
