### ISSUE TITLE
An update action should not include the ID

### ISSUE THREAD

**Issue by davidpelaez** [hanami/model#279]
If you define an alternate primary key in a mapping with 'identity' this is included in the fields to be updated. Consider this query arriving in an SQL server, it was generated with Lotus model of course:

```
UPDATE [CLIENTS] SET [CODE] = N'0001      ', [DIREC1] = N' Le adress', [DIREC2] = N'ALOHA' WHERE ([CODE] = N'0001      ')
```

A validation in the DB complain that I cannot change the primary key. I would assume it makes sense not to send the primary key to be modified or only send the keys that have changed, e.g:

```
UPDATE [CLIENTS] SET [DIREC1] = N' Le adress', [DIREC2] = N'ALOHA' WHERE ([CODE] = N'0001      ')
```

**Comment by AlfonsoUceda** [comment]
@davidpelaez thanks for the issue, but our goal for lotus v0.7.0 is rewrite lotus model

**Comment by jodosha** [comment]
@davidpelaez I see what you mean. Sorry about this trouble. What @AlfonsoUceda was trying to say is that we have the plan to change the internals of Lotus::Model to make them more solid.

I'm leaving this open, because for the next release this problem should be solved. Thanks for reporting this. :+1:

**Comment by davidpelaez** [comment]
Thanks @AlfonsoUceda @jodosha for the info. I'll use a small library for the use case using Sequel directly in the meantime. Glad to hear your are improving Model. It's already awesome but I get the benefits of even greater code.  Looking forward to the updates, best of luck and thank your for contributing this to open source. :)

**Comment by jodosha** [comment]
@davidpelaez Why don't stick with Lotus::Model? That would be **extremely helpful** for us.

We want to improve it, but we need real world feedback to understand if the new direction is valid or not. Does it sounds reasonable for you? Take it as a way to contribute to OSS. :wink:

**Comment by davidpelaez** [comment]
@jodosha I'll be staying, don't worry about it. It's just that the bug affects my ability to work with a legacy SQL Server that I need to connect to for a project that has to be finished within two o three weeks. But I'll be using it for regular Postgres stuff I do in my company. Will you be launching a prerelease or what would be the best way to provide feedback?

**Comment by jodosha** [comment]
@davidpelaez We'll open PR for these changes, I'll ping all the people in chat. Are you in there? https://gitter.im/lotus/chat
