### ISSUE TITLE
Better error for 'deadlock; recursive locking'  - Memory Adapter

### ISSUE THREAD

**Issue by cllns** [hanami/model#285]
A week ago or so I came across a problem where, inside a `query` block, I called another method which called `query`, using the `memory_adapter`. I got this error:

```
     ThreadError:
       deadlock; recursive locking
```

This is because [`query`](https://github.com/lotus/model/blob/master/lib/lotus/model/adapters/memory_adapter.rb#L125) uses a mutex to `synchronize` the query, so it can't recursively call another `query`.

I fixed it by storing the results of the first method that called `query` into a variable, then using that variable inside the `query`.

I think this only affects `memory_adapter`.

Should we catch `ThreadError` and throw a new `Lotus::Error`, with a more helpful error message? Basically just tell the user what happened, and how they can avoid it.

At the very least, if we don't want that, we can close this Issue and it'll show up in search results when people have this problem :)

(Thanks to @angelbotto for reminding me of this issue, in the chat)

**Comment by jodosha** [comment]
@cllns Do you have a concrete example to reproduce the problem?

**Comment by cllns** [comment]
Here you go @jodosha! 
https://gist.github.com/cllns/f8726cbd71b78d1ae5b6

Looking at `by_most_recent_comment_working` and `by_most_recent_comment_broken`, you should be able to see what I was talking about above :)

**Comment by jodosha** [comment]
As of v0.7.0 we don't ship Memory and File System adapters.
