### ISSUE TITLE
Make repositories to work with data

### ISSUE THREAD

**Issue by jodosha** [hanami/model#291]
## Actual

Right now we only accept entities as input for repositories default CRUD operations. This often leads to awkward and unnecessary objects allocations.

``` ruby
book = BookRepository.create(
  Book.new(params[:book])
)
```

That intermediate line is unnecessary. We should adopt the _"data in, entities out"_ principle.
## Proposal

Default CRUD operations should accept any object that respond to `#to_hash`.

``` ruby
book = BookRepository.create(params[:book])
```

To maintain backward compatibility we should implement `Hanami::Entity#to_hash`. In this way, the syntax above will still work. Please notice that `Hanami::Entity` already has `#to_h`, so it's just a matter of alias that method.

All the other objects will work just fine:

``` ruby
➜ pry
[1] pry(main)> require 'rubygems'
=> false
[2] pry(main)> require 'hanami/controller'
=> true
[3] pry(main)> Hanami::Action::Params.new({}).respond_to?(:to_hash)
=> true
[4] pry(main)> {}.respond_to?(:to_hash)
=> true
```

---

The decision to use `#to_hash` over `#to_h` is demanded by the dangerous implementation that some objects like `Array` have.

``` ruby
➜ pry
[1] pry(main)> [].to_h
=> {}
[2] pry(main)> [1].to_h
TypeError: wrong element type Fixnum at 0 (expected array)
from (pry):2:in `to_h'
[3] pry(main)> [['a', 1]].to_h
=> {"a"=>1}
```

There is the risk that a `TypeError` could be raised if an array is passed. Better to rely on `#to_hash`, and keep `Array` out because:

``` ruby
➜ pry
[1] pry(main)> [].respond_to?(:to_hash)
=> false
```

**Comment by booch** [comment]
I hadn't considered the "data in, entities out" idea, but it looks like a good idea. Given that we can still use an entity as input, I don't see the harm in the proposed change.

**Comment by joneslee85** [comment]
Seems a safe change to me.

What's data?

What type of hash should  `to_hash` return? A string vs symbol key hash?

**Comment by Bounga** [comment]
It look really good to me :+1:

It's a huge step forward in term of flexibility.

@joneslee85 I'd like to be able to use both. I think it's simple to handle.

**Comment by jodosha** [comment]
@joneslee85 

> What type of hash should to_hash return? A string vs symbol key hash?

This is an excellent question that opens a new, huge topic. Please keep in mind that most of the times data means a Hash that is coming from a Rack env.

Here's the status of symbol vs string per MRI version.

### MRI 2.0, 2.1

#### Symbol

  * Immutable: VM efficient
  * Non GC'd: security threats

#### String

  * Mutable: less efficient
  * GC'd: no security threats

Until we supported these versions, we had to offer _"indifferent access"_. Internally, data was stored with string keys, because of security reasons.

### MRI 2.2, 2.3

#### Symbol

  * Immutable: VM efficient
  * Non GC'd: security threats

#### String

  * Mutable: less efficient
  * GC'd: no security issues

We can safely go for "symbol only" approach, because it's efficient and because we define all the other attributes with symbols: param validations, entity attributes, database mapping, column names, etc..

This "symbol only" solution has a cost of deeply symbolize the Rack params for each request.

### MRI 3.0

#### Symbol

  * Immutable: VM efficient
  * Non GC'd: security threats

#### String

  * Immutable (?): VM efficient
  * GC'd: no security issues

Probably this version will ship with immutable strings. That can allow us to use a "string only" approach and save us from the perf cost of deep symbolize incoming data. But it's too early to speculate about this change.

---

With this background in mind, we can:

### Leave it as it is: "_indifferent access_"

#### PROs

  * It's well known pattern, and it feels "natural" for many developers
  * It's already implemented
  * It allows us to defer the choice, according to the future of MRI


#### CONs

  * We can't simplify our internals

### Go for "_Symbol only_"

#### PROs

  * Consistent with other components: params definition, entity attributes, database mapping, etc..
  * "Future proof" (?) - Symbol shouldn't change in next major Ruby release
  * It allows to simplify our internals

#### CONs

  * Perf overhead due to deep symbolize

### Go for "_String only_"

#### PROs

  * No perf overhead (keys are already strings)
  * It allows to simplify our internals

#### CONs

  * Inconsistent with other components: params definition, entity attributes, database mapping, etc..
  * We don't know if strings will be efficient as symbols in the future. It will depend on if Ruby 3.0 will include immutable strings.

**Comment by joneslee85** [comment]
@jodosha :+1: on detailed explanation. If I were to cast a vote, I would go for *Symbol only* for the sake of consistency with other components. It helps transition to String (if we decided to adopt it when Ruby 2.x are all dead).

**Comment by jodosha** [comment]
@joneslee85 Me too.

**Comment by booch** [comment]
Small correction to @jodosha's description of symbols versus strings: MRI 2.2 introduced garbage collection of symbols. See http://www.infoq.com/news/2014/12/ruby-2.2.0-released for more details.

**Comment by booch** [comment]
I vote for symbol-only hash keys. That seems to be the preference in most situations in Ruby, especially given the Ruby 1.9+ JavaScript-style `key: value` syntax.

**Comment by jodosha** [comment]
@booch Thanks for let me know. It was a copy and paste mistake :smile: Thanks for expressing your opinion, we appreciate it :+1:

**Comment by solnic** [comment]
This will be supported in the next release of rom-repository. Here's a preview: https://gist.github.com/solnic/b369420c32b1432f6d239db470dbd2d3

Re symbol-vs-strings - of course symbols-only. Indifferent access is such a smell...it's not even funny. Input from http requests should be properly coerced, lower layers shouldn't even know that there's such a thing as params hash with string keys.
