### ISSUE TITLE
Question mark methods for attributes

### ISSUE THREAD

**Issue by cllns** [hanami/model#309]
While developing a program that uses `Hanami::Entity`, I expected I'd have access to [a question mark method](http://api.rubyonrails.org/v4.1/classes/ActiveRecord/Base.html#class-ActiveRecord::Base-label-Attribute+query+methods), which returns whether an attribute is truthy.

For example:
```
class Book
  include Hanami::Entity
  attributes :title, :author
end

book = Book.new(title: "Ruby Ruby Ruby") 
book.author? # ERROR, but should return false since author is not truthy (it's nil)
```

It'd use meta-programming to define those question mark methods for each attribute.  

In my opinion,`book.author?` is much more natural than `!!book.author`

In this case, I wanted to iterate over an array that may or may not exist. Right now I just call `.nil?` on it instead, though I could've done `!!` instead.

Feel free to assign this to me, if this is desired.

**Comment by jodosha** [comment]
@cllns For each added attribute, we increase the interface of that object of two methods: a getter and a setter. This would add a third method, that isn't always needed.

So, if you have 5 attributes, you have 5 question mark methods. It's the case that you want to just check 1 or 2, not all of them.

---

If a developer needs this method, they can add it:

```ruby
def author?
  ! author.nil?
end
```

I'd resist for now to add a Public API feature, unless there is a wild demand for it.

**Comment by cllns** [comment]
Sounds good. 

@hlegius made a great point that it encourages violating "Tell, Don't Ask".
