### ISSUE TITLE
'model' depends on unreleased 'hanami-utils ~> 0.8' gem

### ISSUE THREAD

**Issue by anatol** [hanami/model#318]
Dependency `hanami-utils ~> 0.8` cannot be satisfied as rubygems.org does not know about such version. The last released gem is 0.7.2 https://rubygems.org/gems/hanami-utils

**Comment by jodosha** [comment]
@anatol Thanks for reporting this. It's a mistake of mine 😞 . Today I released `0.7.2` with the wrong dependency.

A new release is on the way.

**Comment by jodosha** [comment]
Released a new version https://rubygems.org/gems/hanami-model/versions/0.6.2.1
