### ISSUE TITLE
hanami db apply fails with postgres 9.5.x

### ISSUE THREAD

**Issue by daniel-ferguson** [hanami/model#321]
```
> hanami db apply
pg_dump: invalid option -- 'i'
Try "pg_dump --help" for more information.
```

The `-i` option was removed in postgres 9.5 - release notes: <https://www.postgresql.org/docs/current/static/release-9-5.html#AEN127317>
> Remove the long-ignored -i/--ignore-version option from pg_dump, pg_dumpall, and pg_restore (Fujii Masao)

`pg_dump` is called with `-i` in the `dump_structure` method of `lib/hanami/model/migrator/postgres_adapter.rb` - removing this flag seems to fix the issue, though I'm not familiar with postgres's history, and whether the flag is used in the adapter to correctly support much older versions of pg.

Thanks! If it would be helpful, I can rustle up a pull request tomorrow.

**Comment by joneslee85** [comment]
@daniel-ferguson thanks for the bug report. I'd suggest that you dig further to learn why Fuji Masao introduced this change. It is only then we could make a good decision how to address this issue.

**Comment by daniel-ferguson** [comment]
That makes sense, thank you.

Flag History
---------------------

After going through PostgreSQL's history, it appears that the `-i` flag started being ignore in version 8.4.
Release notes: <https://www.postgresql.org/docs/current/static/release-8-4.html#AEN150189>
> Remove -i/--ignore-version option from pg_dump and pg_dumpall (Tom)
>
> Use of this option does not throw an error, but it has no effect. This option was removed because the version checks are necessary for safety.

This is also reflected in the docs for `pg_dump` <https://www.postgresql.org/docs/8.4/static/app-pgdump.html>

> -i
> --ignore-version
>  A deprecated option that is now ignored.

Removing this flag would only affect users using a PostgreSQL version older than 8.4 - the last of which is version 8.3.23 - release notes: <https://www.postgresql.org/docs/current/static/release-8-3-23.html>

This was released on the 7th of February 2013 and is unsupported/EOL.

Support & Operating System Packages
-----------------------------------------------------

I have looked at a list of major linux OS flavours to see which versions of PostgreSQL the oldest - still supported versions ship packages for:

8.4 was released in 2009-07-01 and most distributions package > 8.4: 
- Ubuntu LTS 12.04 (EOL late 2017[[1]]) packages 9.1 by default and makes 8.4 available - but not 8.3 or older [[2]][[3]]
- Debian 7.0 (EOL early 2018[[4]]) packages 9.1[[5]] with no option of 8.4 as far as I can tell [[6]]
- CentOS 5 (EOL early 2017[[7]]) *does* package an older version: 8.1 [[8]]
- CentOS 6 (EOL late 2020[[7]]) packages 8.4[[9]]

I couldn't get access to a versioned RedHat package index, but I suspect it similar to CentOS, but probably longer supported. CentOS 5 was released in 2007 as can be seen from timestamps on files in the release archives [[10]]. Support for versions > 8.4 (unaffected by removing the flag) seems good overall, with the exception of old versions of CentOS & RedHat.

RubyGem Support
---------------------------

For `hanami-model` PostgreSQL support, the `pg` gem is generally used. This gem no longer supports versions of PostgreSQL older than 8.4 since commit [[11]] made on the 26th of March 2016. By looking at the git history, it seems that this updated README was included in release `0.15.1` which was made on April the 8th of 2013.

PostgreSQL Lifecycle
------------------------------

PostgreSQL < 9.1 are no longer supported officially by the project: <https://www.postgresql.org/support/versioning/>

Excerpt from above link:
> Version	Current minor	Supported	First release date	EOL date
> 9.1	9.1.22	Yes	September 2011	September 2016
> 9.0	9.0.23	No	September 2010	September 2015
> 8.4	8.4.22	No	July 2009	July 2014

-----------------------------------------------------------------------------

Summary
---------------

PostgreSQL versions prior to 8.4 might be affected by this change, but as indicated above:
* Versions prior to 9.1 are no longer officially supported by the PostgreSQL project.
* Still supported EOL versions of Debian and Ubuntu both ship only versions of PostgreSQL
  which would be unaffected by this change. 
* Old but still supported versions of CentOS & RedHat likely ship versions which could be affected - though they also ship ruby 1.8.5, which I assume Hanami does not support.

I hope this is helpful in terms of making a decision about removing the flag to support PostgreSQL > 9.5.x - if there is any more info that could help, let me know. Rails removed this flag in 4.2.5 - see here for the pull request discussion <https://github.com/rails/rails/pull/21931>

[1]: https://wiki.ubuntu.com/LTS
[2]: http://packages.ubuntu.com/precise/database/postgresql
[3]: http://packages.ubuntu.com/precise/database/postgresql-8.4
[4]: https://wiki.debian.org/DebianReleases
[5]: https://packages.debian.org/wheezy/database/postgresql
[6]: https://packages.debian.org/wheezy/database/
[7]: https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d
[8]: http://mirror.centos.org/centos/5/os/x86_64/CentOS/
[9]: http://mirror.centos.org/centos/6/os/x86_64/CentOS/
[10]: http://vault.centos.org/5.0/
[11]: https://github.com/ged/ruby-pg/commit/1ea7fc6c1d18aec4c37739e1e089032d12d33785

**Comment by jodosha** [comment]
@daniel-ferguson Hi and thanks for this detailed explanation. ✨ 

I'm fine to keep compatibility with latest PG. With #323 We fixed the problem.

**Comment by daniel-ferguson** [comment]
Thanks all :+1:
