### ISSUE TITLE
database username and password

### ISSUE THREAD

**Issue by wendy0402** [hanami/model#326]
Hi guys, currently I am playing around with hanami. It seems interesting, however since coming from rails background and use sql adapter for hanami. At first glance, I confused how to put username and password since the config example only show uri without username and password, such as:

``` ruby
adapter type: :sql, uri: mysql2://localhost/bodyguard2_development
```

my suggestion, It'll be better if you explicitly tell how to add database username and password like this(CMIIW for the URI example ):

``` ruby
adapter type: :sql, uri: mysql2://username:password@localhost:3306/bodyguard2_development
```

by doing so, it'll be easy for newcomers to catch up

thanks

**Comment by jodosha** [comment]
@wendy0402 Thanks for reporting this. The README now mentions username and password in the basic example.
