### ISSUE TITLE
Mapping the same sql table for multiple Entities/Repositories

### ISSUE THREAD

**Issue by vasspilka** [hanami/model#327]
I've been trying to do something like the following

```
mapping do
  collection :users do
    entity User
    repository UserRepository
    ...
  end

  collection :users do
    entity Customer 
    repository CustomerRepository
    ...
  end

  collection :users do
    entity Admin
    repository AdminRepository
    ...
  end
```

to map a `users` table with multiple entities but it seems to only register the last one.

Also I tried doing inheritance to the special user repositories

```
AdminRepository < UserRepository
# only mapping for user
```

but that also failed any ideas? Is this a missing feature?

`hanami-model 0.6.1`

**Comment by beauby** [comment]
As you can see [here](https://github.com/hanami/model/blob/3e99c5682c45264e12ac08f7c479e6c01682f656/lib/hanami/model/mapper.rb#L101), the collection is overwritten each time you call `collection` with the same key.
After a quick glance, my conclusion is that there can be only one mapping per table. Which, I agree, is sad.

**Comment by jodosha** [comment]
@vasspilka This isn't possible with the upcoming 0.7.0, but we can consider it for the future.

**Comment by beauby** [comment]
This is interesting, especially when dealing with legacy databases where it happens that two logical entities are stored in the same table (arguably poor design, factual reality).

**Comment by vasspilka** [comment]
Ecto is now supporting stuff like these, I assume ROM will follow, therefore hopefully we can see this in hanami through ROM

**Comment by solnic** [comment]
rom supports it from the very start, you can configure multiple relations to point to the same table, you can load data from multiple relations into a single entity too, you are free to do whatever you want with the data (in general)

**Comment by jodosha** [comment]
Unfortunately this can't be part of Hanami 1.0.

I'll bring this feature on the discussion table for the post 1.0.
