### ISSUE TITLE
Cannot run db prepare

### ISSUE THREAD

**Issue by TheFarmingBunny** [hanami/model#330]
I am attempting to run `bundle exec hanami db prepare` but I get this error: `Hanami::Model::MigrationError: Current adapter () doesn't support create.` I have already created the database and given myself full privileges. I'm using postgressql

**Comment by Defman21** [comment]
What adapter are you using? 

http://hanamirb.org/guides/models/overview/#adapters

**Comment by TheFarmingBunny** [comment]
SQL with a Postgresql database on localhost

06.08.2016, 19:19, "Sergey Kislyakov" <notifications@github.com>:

**Comment by cllns** [comment]
We should improve that error message, since it's not clear at all.

Is your url is `postresql://` instead of `postgres://`?
https://github.com/hanami/model/blob/3e99c5682c45264e12ac08f7c479e6c01682f656/lib/hanami/model/migrator/adapter.rb#L33

**Comment by TheFarmingBunny** [comment]
I worked out it might be because of `jdbc:` so I removed that and I now get this error: `RuntimeError: Cannot instantiate adapter of Hanami::Model::Adapters::SqlAdapter (LoadError: no such file to load -- pg)`

07.08.2016, 06:01, "Sean Collins" <notifications@github.com>:

**Comment by Defman21** [comment]
Add `gem "postgres"` to your Gemfile and run `bundle install`.

**Comment by TheFarmingBunny** [comment]
I'm using jruby with the `jdbc-postgres` gem

07.08.2016, 14:20, "Sergey Kislyakov" <notifications@github.com>:

**Comment by Defman21** [comment]
Then you should find a package which could be loaded using `require "pg"`.

**Comment by TheFarmingBunny** [comment]
I think we should start using `jruby-pg` instead of `jdbc-postgres` since I have found that it works better.

**Comment by jodosha** [comment]
@TheFarmingBunny Does `jruby-pg` solves your issue?

**Comment by TheFarmingBunny** [comment]
Yes, I created a pull request to add it into the default Gemfile on java platforms

10.08.2016, 11:33, "Luca Guidi" <notifications@github.com>:

**Comment by jodosha** [comment]
@TheFarmingBunny I'm closing this as I discovered that `jruby-pg` is [outdated](https://github.com/headius/jruby-pg/commits/master).

The upcoming `hanami-model` v0.7.0 (in master now), supports JRuby and PG via `jdbc-postgres` and it works well. Please check if this gem works for you too.
