### ISSUE TITLE
created_at forget about timezone after persisting to PG 

### ISSUE THREAD

**Issue by brbrr** [hanami/model#335]
Im persisting new record in to Postgres:
```
irb(main):031:0> tr = TriggerRepository.create(Trigger.new(type: 'hours1'))
=> #<Trigger:0x007f9537112a00 @id=88 @type="hours1" @views=nil @created_at=#<DateTime: 2016-10-04T07:54:42+00:00 ((245766
6j,28482s,814091000n),+0s,2299161j)> @updated_at=#<DateTime: 2016-10-04T07:54:42+00:00 ((2457666j,28482s,814091000n),+0s,
2299161j)>>
irb(main):032:0> t = TriggerRepository.last
=> #<Trigger:0x007f9537108b18 @id=88 @type="hours1" @views=0 @created_at=#<DateTime: 2016-10-04T07:54:42+03:00 ((2457666j
,17682s,814091000n),+10800s,2299161j)> @updated_at=#<DateTime: 2016-10-04T07:54:42+03:00 ((2457666j,17682s,814091000n),+1
0800s,2299161j)>>
```

Here is my project: https://github.com/brbrr/message_app

After loading that record from db - `DateTime` uses my local Time zone instead of 00:00

**Comment by beauby** [comment]
As you can see [here](http://hanamirb.org/guides/migrations/create-table/#type-definition), if you specify `DateTime` as a type for your `created_at` field, it will be created as a `timestamp` field within postgres, which defaults to `timestamp without time zone`. So what you want is to mutate this field into a `timestamp with time zone` (official SQL type), or `timestamptz` (postgres-specific abbreviation of the previous).

**Comment by beauby** [comment]
Can we close this?

**Comment by brbrr** [comment]
Its solved. Thanks!
