### ISSUE TITLE
Expose pre-mapped relations

### ISSUE THREAD

**Issue by beauby** [hanami/model#343]
## Current behavior

Currently, instances of `Hanami::Repository` expose the underlying `ROM::Relation`s directly as methods with names those of the SQL table. I.e. `class UserRepository < Hanami::Repository; end` will have a `users` method defined that returns the `ROM::Relation` for the `users` SQL table (along with all the other existing relations).

This allows for code that looks like this:
```ruby
class UserRepository < Hanami::Repository
  def most_recenty_modified_user
    users.order(:updated_at, :desc).first # Not sure about the `order` API but it does not matter.
  end
end
```

This method will return an instance of `ROM::Struct[User]`.
```ruby
UserRepository.new.most_recently_modified_user  # => <ROM::Struct[User]:0xdeadbeef ...>
```

In order to get an actual `User` entity returned, a call to `RelationProxy#as` has to be chained:
```ruby
class UserRepository < Hanami::Repository
  def most_recenty_modified_user
    users.order(:updated_at, :desc).first.as(User)  # or .as(:entity) because :entity is a Hanami-defined ROM mapper that basically does the same as automapping to the entity class, except it fails for aggregates.
  end
end
```
The method will now return an instance of `User`.
```ruby
UserRepository.new.most_recently_modified_user  # => <User:0xcafebabe ...>
```

## Issue

The issue is that more often than not, hanami users will overlook that `.as(User)` call and (rightfully) complain that their app is crashing because they have no idea what this `ROM::Struct` is (or even what ROM is for that matter).

The point is, Hanami::Model **is not ROM**. It is implemented with ROM, which is really cool, but it is a repository/entity API, and should thus deal with repositories and entities (and not expect users to have an in-depth knowledge of the underlying implementation and its data structures). 

## Proposed solution

A possible solution would be to have the exposed relations auto-map to the corresponding entities, such that the first example returns a `User` entity instead of a `ROM::Struct[User]`.

In order not to penalize users with advanced use-cases that may need access to the bare ROM relation, I suggest it could be exposed prefixed with an underscore (i.e. `users` is the pre-mapped relation, and `_users` is the bare ROM relation).

**Comment by jodosha** [comment]
@beauby This completely makes sense. Thanks for taking time to write an extended explanation of the problem.

IMO this should be included in 1.0.
