### ISSUE TITLE
Perform raw sql in a Hanami::Repository subclass

### ISSUE THREAD

**Issue by choallin** [hanami/model#345]
I our app (pre 0.9) we use raw sql statements quite often to use our database to the fullest. To be able to upgrade to version 0.9 we would really need to have something similar like the fetch/execute methods that used to be available.
Can this be done right now?

**Comment by solnic** [comment]
There's no public API in hanami for this at the moment, but you *can* do that with rom easily. Before I show you how, please tell me what exactly you need in terms of the query results. ie do you just want plain hashes back, or do you need to map them to entities or some other custom objects?

**Comment by choallin** [comment]
Right now we handle the initialisation of the entities on our own after we get the fetched result. I.e. a hash is all we need.

**Comment by jodosha** [comment]
@choallin Hey, can you please give a look at https://github.com/hanami/model/pull/354 ? Thanks.

**Comment by jodosha** [comment]
@choallin Hey, I closed #354 in favor of #362. Please check it! 😄

**Comment by jodosha** [comment]
Fixed by #362
