### ISSUE TITLE
Support for Namespaced Repositories

### ISSUE THREAD

**Issue by mereghost** [hanami/model#347]
There should be a way to support a `NamespaceDomain::StuffRepository`.

Currently it complains about the relation name (it tries to use something along the lines of  `namespacedomain/stuffs`), if you set the relation name, you have to setup  the mapping or else it complains about some method (`first` IIRC) being sent to `nil` and even then it still does not work.

**Comment by jodosha** [comment]
Yes, I think this is a feature that we should consider. 👍 

@mereghost Can you please investigate what changes are needed here and in `hanami` to make it to work? Eg. how to deal with model generators?

**Comment by cllns** [comment]
I agree! 

My two cents: I'd prefer generating the files like:
```
module NamespaceDomain
  class StuffRepository
    # ...
  end
end
```
rather than
```
class NamespaceDomain::StuffRepository
  # ...
end
```
That way, code within the same namespace can be used easily. :)

**Comment by beauby** [comment]
@jodosha In terms of generators it would be quite straightforward. The "hard" part would probably be to ensure that namespaced repositories use the "right" relation (which brings the question of what happens when two repositories have the same name, but in different namespaces).

**Comment by mereghost** [comment]
@beauby Hmmm. Can you come up with a use case that would generate that problem? I'm not sure if the namespace should be reflected on the relation name as I usually namespace things to isolate behavior in bundles of functionality. That, in itself, shouldn't duplicate entities (or repositories for that matter).

**Comment by beauby** [comment]
@mereghost You could be running two websites, one for users, one for admins, with two distinct `session` databases, and both `Users::SessionRepository` and `Admins::SessionRepository`. I think being able to specify the underlying relation painlessly should solve all problems.

**Comment by solnic** [comment]
In rom-repository it is possible to specify relation identifier via `ROM::Repository[rel_name]` like this:

``` ruby
class MyRepo < ROM::Repository[:user_sessions]
end
```

So, I'm wonder if that would just work with hanami repos:

``` ruby
module Users
  class SessionRepository < Hanami::Repository[:user_sessions]
  end
end
```

If you don't like that syntax, you can just specify root relation of a repository like that:

```
module Users
  class SessionsRepository < Hanami::Repository
    root :user_sessions
  end  
end
```

I can see that hanami repositories define their own `relation` class attribute though...so, if that one is used in other places, then we've got a small problem to solve, but it shouldn't be hard :)

**Comment by mereghost** [comment]
Thanks for the info @solnic . I'll (finally) take a look at this issue.

**Comment by jodosha** [comment]
@mereghost To solve the relation name problem you described in the description. What you should do is to add `demodulize` here, before `underscore`: https://github.com/hanami/model/blob/master/lib/hanami/model/relation_name.rb#L20

**Comment by mereghost** [comment]
@jodosha Nice! That method escaped my notice before.

**Comment by jodosha** [comment]
I'm closing this a stale proposal. If somebody wants to take action, you're more than welcome.
