### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by jodosha** [hanami/model#35]
Support associations between collections.

``` ruby
Lotus::Model::Mapper.new do
  collection :articles do
    # ...
    association :comments, [Comment]
  end

  collection :comments do
    # ...
    association :article, Article, foreign_key: :article_id 
  end
end
```

The first association is `1-n`, where an article has many comments. The `[]` syntax specifies this.

The second association is `n-1`, where a comment belongs to an article (lack of `[]`). The `foreign_key` should be optional and only specified when the following convention isn't respected: association name + `_id`. In the example above: `article` + `_id`.

Associations MUST NOT be loaded by default, but they require an explicit intervention via the `preload` method (which should be implemented as part of this feature).

``` ruby
class ArticleRepository
  include Lotus::Repository

  def self.by_author(author)
    query do
      where(author_id: author.id)
    end.preload(:comments)
  end
end
```

**IMPORTANT:** Let the preload mechanisms to not work with SQL joins, but **with repositories** instead. This isn't efficient, but we have a gain in terms of flexibility. Imagine the the scenario where the comments above aren't stored in the local database, but fetched from a remote JSON API. Thanks to the mapper we can easily know where to fetch those comments.

**Comment by Extazystas** [comment]
Is it official part of lotus model?
If yes, why its not mentioned in Readme?

**Comment by AlfonsoUceda** [comment]
No, it isn't

**Comment by pascalbetz** [comment]
How would associations work for the insert/remove workflow (adding a comment to/removing a comment from an article)? I guess there'd be no support from lotus/model as it's only a "stupid" ruby object?

About the syntax for declaring assocations: 
Defining associations with/without ```[]```to indicate has many/ belongs to seems a bit limited (as @coenert already pointed out with the has one case (foreign key on the other end)). I'd prefer something more speaking, like the inline version from @coenert.

Sidenote:
I'm new to lotus and doing a lot of Rails currently

**Comment by jodosha** [comment]
@pascalbetz Thank you for your opinion. The workflow for add/remove associated records is something under discussion. We're trying to apply a simple design her. :smile:

**Comment by pascalbetz** [comment]
@jodosha

If i understand correctly:

associations are just "stupid" getters/setters. So there is no syncing between the foreign key attribute and the association?

(pseudocode)
```
article = Article(id: 1, ....)
p article.user_id => nil

user = User(id: 10, ...)

article.user = user
p article.user_id => 10
```

I guess you don't want to autogenerate methods like
```
def user=(user)
  self.user_id= user.try(:id)
  @user = user
end
```
on the entity?

**Comment by pascalbetz** [comment]
@coenert 

Wouldn't the collection/fk/... options be arguments to belongs_to? (assuming _belongs_to_ is a method which returns a type which represents the association)
```
attribute :author, belongs_to(User, collection: :users, foreign_key: :author_id)
```

**Comment by coenert** [comment]
@pascalbetz Probably, but now after some time i think my suggested api isn't in any way simpeler to understand then the one @jodosha initially suggested. I think i missed the point of creating less magic DSL's to reduce complexity(still learning :smile:)

**Comment by pascalbetz** [comment]
@coenert

The proposed API by @jodosha might hit some limits though (has and belongs to many, has many through).

How about 

```ruby
attribute :user_id, Integer...
belongs_to :user, User, foreign_key: :user_id, ...
has_many :comments, Comment
```
Pretty much like Rails does it. Just keep the associated class as the second argument.

**Comment by kirantpatil** [comment]
Sir, Any updates on this issue ?

**Comment by joneslee85** [comment]
@kirantpatil we are in the cycle of improving model so please stay tuned.

**Comment by Defman21** [comment]
Are you still in the cycle of improving Model? I'm missing any sort of relations between tables.

**Comment by cllns** [comment]
@Defman21 Yup. @jodosha is working on changing the backend of `hanami-model` to use [Ruby Object Mapper (rom)](http://rom-rb.org/). He's started it on the `new-engine` branch, so you can check it out there, but it's in progress and the docs don't reflect the changes.

**Comment by Defman21** [comment]
I'm happy to see that there's some work going on for solving this issue :)

**Comment by lleolin** [comment]
In lieu of hanami-model, what would be the downsides of just straight-up using rom? What will hanami-model provide that rom doesn't right now?

**Comment by solnic** [comment]
hanami-model will provide more conventional usage than "plain rom" which comes with various conveniences like model inference, auto-timestamps, auto-field renaming etc. Pretty much what you would expect from a full-stack framework.

**Comment by senei** [comment]
`attribute :author, belongs_to(User, collection: :users, foreign_key: :author_id)`

returns error **_uninitialized constant Book::User (NameError)_** -- why 
in db it is working correctly

**Comment by beauby** [comment]
@senei Please open a separate issue.

**Comment by jodosha** [comment]
@senei Where did you found that syntax? And where it is used?

**Comment by jodosha** [comment]
I'm closing this in favor of future, smaller, focused, and actionable proposals.
