### ISSUE TITLE
Customisations of Sequel

### ISSUE THREAD

**Issue by vladra** [hanami/model#352]
Sometimes there is a need to access lower level details of hanami-model to configure some use case specific stuff.

For example, if there are infinite timestamps in DB, Sequel will throw error. With access to the Sequel connection this could be easily solved:
`connection.convert_infinite_timestamps = 'nil'`

There are some other possible cases when this would be helpful. Such as DB sharding, transactions, turning on specific Sequel plugins, etc

It could be useful to have access to configuration details, which are hidden right now

@jodosha ticket as result of gitter chat discussion

**Comment by jodosha** [comment]
@vladra Hi, would you please review https://github.com/hanami/model/pull/367 ? It introduces a DSL to customize the connection. Thanks!
