### ISSUE TITLE
mapping (Hanami::Model::Error)

### ISSUE THREAD

**Issue by panthomakos** [hanami/model#360]
I get a `mapping (Hanami::Model::Error)` when running [this simple program](https://gist.github.com/panthomakos/7e3a5c3745b8ab729bb3ac1a68a3eb0a). Can you explain why this is happening; and how the issue can be resolved?

**Comment by mereghost** [comment]
It seems that the SQL Configuration for `hanami-model` isn't loaded by default.

You will need to require `hanami/model/sql` to make it work. This file is the one that really registers all the plugins used with `rom`.

That being said, we should update the documentation to reflect that.

**Comment by AMHOL** [comment]
BTW you can run your migrations using `Hanami::Migration` rather than using Sequel directly, see https://gist.github.com/AMHOL/222b175c0c375184fb4b0351cd3c7c77

**Comment by AlfonsoUceda** [comment]
@panthomakos did you fix your problem?

**Comment by panthomakos** [comment]
Yes, requiring `hanami/model/sql` fixed the issue. Thanks!

**Comment by AlfonsoUceda** [comment]
Thanks @panthomakos

**Comment by Naniakl3** [comment]
How to configure database in hanami. I am using pg.

**Comment by mereghost** [comment]
@Naniakl3 Considering your are running the latest stable version, there should be an `.env.development` (and a `.env.test`) file on your project. There you will find a variable that holds the database connection string.

Edit that and you should have DB access.
