### ISSUE TITLE
Migrations fail when using mysql and utf8mb4

### ISSUE THREAD

**Issue by mfinelli** [hanami/model#364]
The default schema_migrations table creates a primary key varchar(255) which exceeds the maximum size for an index.

`Sequel::DatabaseError: Mysql2::Error: Specified key was too long; max key length is 767 bytes`

The size of the filename key should change to varchar(190).

This currently prevents running _any_ migrations (since we can't create the schema_migrations table.

**Comment by TiteiKo** [comment]
Hi @mfinelli 

This is a bug you should be reporting on [Sequel github issues](https://github.com/jeremyevans/sequel)
As Hanami model uses Sequel's migrations, I'm sorry to say that there's nothing we can do about your issue here.

**Comment by mfinelli** [comment]
Thanks, I've opened the following issue: https://github.com/jeremyevans/sequel/issues/1282

**Comment by jodosha** [comment]
@mfinelli Thank you :smile:

**Comment by mereghost** [comment]
BTW it's due to default collation and [mysql limitations](https://bugs.mysql.com/bug.php?id=6604).
