### ISSUE TITLE
Migrations should support unsigned integers

### ISSUE THREAD

**Issue by mfinelli** [hanami/model#365]
It would be nice if we could specify unsigned integers in migrations

`column :test, Integer, unsigned: true`

**Comment by TiteiKo** [comment]
Hi @mfinelli 

Hanami model uses Rom which uses Sequel. You can see available column types [here](http://sequel.jeremyevans.net/rdoc/files/doc/schema_modification_rdoc.html#label-Column+types). You can use a string as column type, so the following works:
```ruby
column :test, 'INT UNSIGNED'
```
