### ISSUE TITLE
`rescue in create': comparison of String with 0 failed (Hanami::Model::Error)

### ISSUE THREAD

**Issue by panthomakos** [hanami/model#369]
I get a comparison of `String` with `0` failed exception when trying to create a Hanami Model that doesn't use an auto-increment primary key. Can you help explain what I am missing here?

https://gist.github.com/panthomakos/11fb27801014e557a9a67e9fbc31c05b

**Comment by jodosha** [comment]
@panthomakos Hi I'm sorry about this problem, but we don't support primary key that isn't a serial ID as number.
