### ISSUE TITLE
Class methods in repositories

### ISSUE THREAD

**Issue by Nondv** [hanami/model#373]
Hi guys!
I think there was a discuss on this topic, but I couldn't find it:(
I am new to Hanami (just playing around with it)

Why do you use instance methods instead of class methods?
I mean, I can think of some reasons on my own, but can't we add something like this:

```ruby
class Hanami::Repository
  def method_missing(m, *args)
    return new.send(m, *args) if instance_methods.include?(m.to_sym)
    super
  end
end

SomeRepository.new.all == SomeRepository.all
```

and if not, why?

Sorry for my english

**Comment by AlfonsoUceda** [comment]
Hi @Nondv 
This is the original issue https://github.com/hanami/model/issues/290
