### ISSUE TITLE
Overwrite/Add attributes to inferred entity

### ISSUE THREAD

**Issue by choallin** [hanami/model#385]
With rom-sql it is possible to infer a schema but override just a few attributes for specific purpose. (See [here](http://rom-rb.org/learn/core/schemas/) under Inferring Schemas)
It would be great if we could have this option too, maybe even just add some (meta data) attributes so we can define some special attributes without the need to write the whole schema definition in the entity
Maybe it could work quite similar to rom like so: 
```ruby
  attributes(infer: true) do
    attribute :users, Types::Collection(User)
   # some other meta attributes
  end
```

**Comment by jodosha** [comment]
@choallin Hi, how your proposal is different from this? http://hanamirb.org/guides/models/entities/#custom-schema

**Comment by choallin** [comment]
@jodosha At the end of the guide it states this:
> Custom schema takes precedence over automatic schema. If we use custom schema, we're need to add manually all the new columns from the corresponding SQL database table.  

The difference now is, that because of the `infer: true` the entity gets automatically all attributes from the database but you can overwrite some of them like it is possible in rom (see link above) or you can define the meta attributes as it is necessary for has_many/has_one/belongs_to without the need to define every attribute in the database as well.

**Comment by jodosha** [comment]
@choallin I'm sorry but this will unnecessary complicate _custom schema_ implementation. Associations like `has_many` are already handled by the _automatic schema_. As long we'll add more associations they will be available to the _automatic schema_ as well.

**Comment by glaszig** [comment]
similar issue here. i'm trying to force hanami to de-/serialize a sqlite text column with json. for that, i need to set my column type.

```
class ItemRepository < Hanami::Repository
  schema do
    attribute :meta, Hanami::Model::Types::String.constructor(&JSON.method(:dump))
  end
end
```

of course, this does not work because i now need to define my entire schema myself. but when i do that, the associations don't work anymore. it's a pain.
