### ISSUE TITLE
Migrate from Minitest to RSpec

### ISSUE THREAD

**Issue by jodosha** [hanami/model#392]
A few rules to follow:

  * If you want to work on this, please leave a comment here. We want to avoid many people to work on the same task.

  * We expect this migration to happen within a week from now.

  * Do not change the tests, only migrate from Minitest to RSpec syntax. If not sure, please ask here.

  * Do not remove the old tests, only add the new ones.

  * Make CI build to use RSpec tests.

  * **Target `develop` branch, instead of `master`.**

  * All the tests artefacts like fixtures, goes under `spec/support`.

  * Try to reflect the structure under `lib/`. Eg. `lib/hanami/view.rb` should be tested under `spec/hanami/view_spec.rb`, while `test/rendering_test.rb` should go under `spec/integration/rendering_spec.rb`.

If you want to take inspiration, please have a look at: https://github.com/hanami/mailer/pull/67

**Comment by tejasbubane** [comment]
I would like to work on this.

**Comment by AlfonsoUceda** [comment]
@tejasbubane go ahead ;)

**Comment by zenspider** [comment]
Can you please record some baseline numbers from minitest (probably from the CI) such that you can compare to the rspec version? # tests run, % passed, # assertions/expections, and time to run (and memory RSS if you can!)?

**Comment by jodosha** [comment]
@zenspider Yes, of course.

**Comment by morrme** [comment]
@tejasbubane  Are you still working on this task?  How's it going?

**Comment by tejasbubane** [comment]
Working on it. Was on holidays for a few days. Will send a PR soon.

**Comment by jodosha** [comment]
@tejasbubane ping.

**Comment by jodosha** [comment]
Implemented by #396
