### ISSUE TITLE
relation override must be symbol to avoid error "undefined method `first' for nil:NilClass"

### ISSUE THREAD

**Issue by kaikuchn** [hanami/model#399]
@andru1989 reported a difficult to debug error in the hanami chat on [25. April 2017 00:45](https://gitter.im/hanami/chat?at=58fe7ff58fcce56b2032d087). A look at the [implementation of one of his  repositories](https://gitter.im/hanami/chat?at=58ff7a526aea30763d3f50ce) revealed the source of the error.
[The guides](http://hanamirb.org/guides/models/repositories/#legacy-databases) show an example of manually specifying the relation with a symbol, but do not stress the point that it has to be a symbol.

Nil errors are notoriously difficult to debug. It is therefore that, while this was in the end an error due to wrong use of the Repository API, I do believe a better error would be beneficial. That way users will know what went wrong and how to fix it without first having to consult documentation or seek other help.

PS: I took the liberty of reporting this in @andru1989's stead since the incident was over a week ago and I wanted it off my plate. Hope nobody minds 😁

**Comment by mereghost** [comment]
Code in question:

```ruby
require "hanami/model" 
module Mobijob 
  module Repositories
    class AccessTokenRepository < Hanami::Repository
      include Mobijob::Repositories::ApplicationRepository 
      self.relation = 'access_tokens' 
      self.entity_name = Hanami::Model::EntityName.new("Mobijob::Entities::AccessToken") 
    end
  end
end
```
