### ISSUE TITLE
Invalid URI error

### ISSUE THREAD

**Issue by bigtunacan** [hanami/model#402]
If you have the @ symbol in your password, which is allowed by Postgres for example, an invalid URI error is raised.

Example: 

DATABASE_URL="postgresql://username:p@ssword@localhost/bookshelf_test"

**Comment by kaikuchn** [comment]
Any significant symbols must be URL encoded, otherwise the URL parser cannot process the URL. Postgres will happily decode the URL https://www.postgresql.org/docs/current/static/libpq-connect.html#AEN45571

**Comment by jodosha** [comment]
@bigtunacan Thanks for reporting this. It looks like it's a Sequel bug. I'm gonna report it there.
