### ISSUE TITLE
DB apply command removes migrations even if fail

### ISSUE THREAD

**Issue by rybex** [hanami/model#408]
Hi,

It isn't major bug but I had following inconsistency on my local environment:

```
pg_dump: server version: 9.6.3; pg_dump version: 9.5.5
pg_dump: aborting because of server version mismatch
pg_dump: server version: 9.6.3; pg_dump version: 9.5.5
pg_dump: aborting because of server version mismatch
```

When I used the `bundle exec hanami db apply` command it didn't filled up the `schema.sql` file but still removed all my migrations. Fortunately we have git ;P

**Comment by jodosha** [comment]
@rybex I'm sorry about this problem. Even if it's a minor one, we aim to have the most frictionless user experience for our devs.

Would you mind to try this fix? https://github.com/hanami/model/pull/421 Thank you.
