### ISSUE TITLE
Wrong number of arguments initializing Associations::BelongsTo

### ISSUE THREAD

**Issue by gohkhoonhiang** [hanami/model#414]
I have the following associations in my repositories:

```
class CreditRepository < Hanami::Repository
  associations do
    has_many :credit_attempts
  end
end
```

```
class CreditAttemptRepository < Hanami::Repository
  associations do
    belongs_to :credit
  end
end
```

Now I'm trying to load `credit_attempt` with `credit` by the following method:

```
class CreditAttemptRepository < Hanami::Repository
   def find_with_credit(id)
     assoc(:credit).where(id: id).as(CreditAttempt).one
   end
end
```

Then I get the following error:

```
[1] pry(main)> credit_attempt = CreditAttemptRepository.new.find_with_credit(1)
ArgumentError: wrong number of arguments (given 4, expected 0)
from .../lib/hanami/model/association.rb:18:in `initialize'
```

Upon looking into the source code, I find out that there is no `initialize` method defined in `Associations::BelongsTo`, which was used somewhere in `hanami/model/association.rb`:

```
def self.build(repository, target, subject)
  binding.pry
  lookup(repository.root.associations[target])
    .new(repository, repository.root.name.to_sym, target, subject)  # <-- trying to initialize with 4 arguments
end

def self.lookup(association)
  case association
  when ROM::SQL::Association::OneToMany
    Associations::HasMany
  when ROM::SQL::Association::ManyToOne
    Associations::BelongsTo    # <-- this was being returned
  else
    raise "Unsupported association: #{association}"
  end
end
```

Is this WIP or should I not use `assoc` to join the 2 models in the repository? Do you have any other suggestion how I could load the `credit` together with `credit_attempt`?

Many thanks!

**Comment by genya0407** [comment]
@gohkhoonhiang The `wrong number of arguments` error might be solved on the `develop` branch. Could you test the same code on `develop`?

**Comment by gohkhoonhiang** [comment]
@genya0407 This works on `develop`. Do you know when will this feature be released next? Thanks!

**Comment by genya0407** [comment]
@gohkhoonhiang I don't know since I'm not owner/contributor of hanami :)

**Comment by gohkhoonhiang** [comment]
@genya0407 No problem. Thanks for being so helpful! :D

**Comment by mereghost** [comment]
@gohkhoonhiang Sorry for missing this earlier. Yeah, we intend to association support for many-to-1, 1-to-1 and many-to-many on 1.1. =)

**Comment by gohkhoonhiang** [comment]
@mereghost Thanks for the heads-up! Will look out for 1.1 release. =D
