### ISSUE TITLE
Can't specify encoding in migrations for MySQL tables/columns

### ISSUE THREAD

**Issue by greggilbert** [hanami/model#417]
I can't find anything in the documentation or code on how to set the encoding/collation for a MySQL database. I tried something like `column :foo, String, null: false, encoding: :utf8mb4` but that doesn't seem to have any effect. There's nothing in the rom-rb docs either that I can find. Is this not supported?

**Comment by cllns** [comment]
Can you try [`charset` instead of `encoding`](http://sequel.jeremyevans.net/rdoc/classes/Sequel/Database.html)?

**Comment by greggilbert** [comment]
@cllns I thought hanami/model is using rom-rb, not Sequel?

**Comment by cllns** [comment]
@greggilbert Indeed, but `rom-sql` relies on `sequel` :) https://github.com/rom-rb/rom-sql/blob/master/rom-sql.gemspec#L18

**Comment by jodosha** [comment]
@greggilbert @cllns We use `sequel` directly for migrations. See: https://github.com/hanami/model/blob/163b1958f58930af622ce00bd58324e6274e5c10/lib/hanami/model/migrator/adapter.rb#L81

---

I'm closing this as you found an answer. 👍
