### ISSUE TITLE
Allow to use ROM plugins in hanami-model

### ISSUE THREAD

**Issue by davydovanton** [hanami/model#420]
You can find many useful plugins for ROM library, for example, [pagination](https://github.com/rom-rb/rom-sql/blob/master/lib/rom/sql/plugin/pagination.rb). Also, you can create own plugin too. WDYT if we add the ability for using ROM plugins in hanami apps?

I had a discussion about it with @flash-gordon, and he told me that we need update [`Hanami::Repository::define_relation`](https://github.com/hanami/model/blob/master/lib/hanami/repository.rb#L145-L157) method. If you do not mind, I will make a PR.

**Comment by cllns** [comment]
👍

**Comment by jodosha** [comment]
@davydovanton please do 👍

**Comment by jodosha** [comment]
Closing this as stale, but marked _for future consideration_, as it we want probably to have this enhancement in 2.0.
