### ISSUE TITLE
Add multiple records in one query.

### ISSUE THREAD

**Issue by genya0407** [hanami/model#426]
Is there any way to `add` multiple records in one query?

What I wanna do:
```ruby
class ArticleRepository < Hanami::Repository
  assocations do
    has_many :categories
  end

  def add_category(article, names)
    data = names.map { |name| { name: name } }
    assoc(:categories, article).add(data)
  end
end
```

However, above code raises error: `NoMethodError: undefined method 'merge' for [{:name=>'hoge'}, {:name=>'fuga'}, {:category_id=>'piyo'}]:Array`.

I know I can do it by issuing query for each time:

```ruby
class ArticleRepository < Hanami::Repository
  assocations do
    has_many :categories
  end

  def add_category(article, names)
    datas = names.map { |name| { name: name } }
    datas.each do |data|
      assoc(:categories, article).add(data)
    end
  end
end
```

However this will produce performance problem.

Is there any cleverer way to do that?

Thanks.

**Comment by jodosha** [comment]
@genya0407 Thanks for the feedback. I'm working on a patch to allow this.

**Comment by AlfonsoUceda** [comment]
@genya0407 sorry for the late answer. Please can you try the following described here? https://github.com/hanami/hanami.github.io/pull/333/files Thanks

**Comment by AlfonsoUceda** [comment]
@genya0407 is it worked?

**Comment by genya0407** [comment]
@AlfonsoUceda sorry for late reply.

In that way, I will write code like this:

```
class ArticleRepository < Hanami::Repository
  assocations do
    has_many :categories
  end

  def add_category(article, names)
    data = names.map { |name| { name: name } }
    ArticleCategoryRepository.new.create_many(datas)
  end
end
```

Is that okay to use another `Repository` in a `Repository`'s method?

By the way, `SomeRepository#create` method seems to be able to do `create_many`, though it doesn't return all records (first created record is returned).

```ruby
BookRepository.new.create([{ title: "Hanami" }, { title: "Ruby"}]) # => this works
```

**Comment by AlfonsoUceda** [comment]
Yeah, no problem, tell us if that work for you.

**Comment by genya0407** [comment]
Then, it worked. Thanks!

**Comment by AlfonsoUceda** [comment]
Closing then, thanks to you.

**Comment by Drenmi** [comment]
@AlfonsoUceda: It seems that using the [example](https://github.com/hanami/hanami.github.io/pull/333/files) in the guide with an entity that has timestamps will fail if not explicitly setting the timestamps.

> FooRepository::#create_many#test_0001_creates several foos in one go:
ROM::SQL::NotNullConstraintError: PG::NotNullViolation: ERROR:  null value in column "created_at" violates not-null constraint
