### ISSUE TITLE
Deprecation warning when passing string to `Repository#where`.

### ISSUE THREAD

**Issue by genya0407** [hanami/model#427]
When I do:

```ruby
class MeetingRepository
  def in_time(now: Time.now)
    meetings
      .where('deadline > ?', now)
      .order(:date)
      .limit(10)
      .to_a
  end
end
```

`where('deadline > ?', now)` produces warning:

"""
SEQUEL DEPRECATION WARNING: Calling a dataset filtering method with multiple arguments or an array where the first argument/element is a string is deprecated and will be removed in Sequel 5.  Use Sequel.lit("deadline > ?", 2017-08-06 18:17:05 +0900) to create an SQL fragment expression and pass that to the dataset filtering method, or use the auto_literal_strings extension.
"""

As the warning states, I used `auto_literal_strings` extension of Sequel:
```ruby
# config/initializers/sequel.rb

Sequel.extension :auto_literal_stringsse
```

However, the deprecation warning still raises.

Is there any way to do `where('deadline > ?', now)` without the above warning?

Or, is this the problem of ROM?

Thanks.

**Comment by rafaels88** [comment]
This is not going to solve your problem because I think coupling your Repositories (or on your configurations) with Sequel is a bad thing, but if you want to avoid the warning, you can literally do what the warning is asking:

`where(Sequel.lit('deadline' > ?, now))`

**Comment by genya0407** [comment]
Ah, I misunderstood the warning.
I'll try `where(Sequel.lit('deadline' > ?, now))` .

Thanks.

**Comment by flash-gordon** [comment]
This can be done without falling back to Sequel with `where(meetings[:deadline] > now)` or `where { deadline > now }`.

**Comment by genya0407** [comment]
@flash-gordon Cool! I love this. Thanks!
