### ISSUE TITLE
createdb not in PATH error message

### ISSUE THREAD

**Issue by cllns** [hanami/model#429]
I opened issue #264 a couple years ago, but I just ran into it again. The error is a little better now, but it should be more informative.

I'm using Postgres.app on OS X, and I just ran into a problem running `hanami db create` where I didn't have `createdb` in my `PATH`.

The error that's displayed is: `Hanami::Model::MigrationError: No such file or directory - createdb` which is only slightly helpful. Instead, I think we should say something like `Hanami::Model::MigrationError: Could not find the executable 'createdb' in your PATH`.

What do you all think?

**Comment by jodosha** [comment]
@cllns Make it happen! 👍

**Comment by AlfonsoUceda** [comment]
Closing it, PR: #435
