### ISSUE TITLE
Repository assumes that primary key is integer

### ISSUE THREAD

**Issue by graywolf** [hanami/model#433]
It seems to me, that repository assumes that primary key is integer. When I have schema

```
primary_key [:name, :version]

column :name, String
column :version, String
```

and I print it in repository via

```
statuses.schema
```

I see that both `name=:name` and `name=:version` are `ROM::SQL::Attribute[Integer]` descpite schema specifying them as string.

**Comment by mereghost** [comment]
Pinging @solnic or @flash-gordon for clarification, as it seems that `rom` infers PKs as Integers.

**Comment by flash-gordon** [comment]
@mereghost it depends on the database actually, by default it's integers, PG's inferrer works differently. @graywolf what DB are you using?

**Comment by graywolf** [comment]
@flash-gordon in this case it was just sqlite3

**Comment by flash-gordon** [comment]
so, atm inferring non-integer PKs is supported on PG only

**Comment by mereghost** [comment]
@flash-gordon Thanks for the heads up. Any idea if that's some kind of limitation of the underlying libs (making it almost impossible to work) or just a `NotImplementedError`? ;)

**Comment by flash-gordon** [comment]
@mereghost it just works like that atm, absolutely nothing prevents from having support for inferrable PKs with other DBs :)

**Comment by mereghost** [comment]
Closing this for now as it's more dependant on `rom-sql` than on hanami aaaand we intend to move to a more modern `rom` asap.
