### ISSUE TITLE
mongodb support?

### ISSUE THREAD

**Issue by ekremkaraca** [hanami/model#436]
Hey guys,

is it possible to add mongodb support for near future? Do you have any plans for this?

**Comment by mereghost** [comment]
@ekremkaraca right now we depend on `rom` so it would be possible to support it, using `rom-mongo`, which is still in its very early stages. AFAIK support for `nosql`  is not on the horizon right now.

OTOH you can always remove the `hanami-model` gem from your Gemfile and use something like 'mongoid`.

**Comment by mereghost** [comment]
Oh! Also you can always reach us on [gitter](https://gitter.im/hanami/chat) for questions, feedback and help =)

**Comment by davydovanton** [comment]
@ekremkaraca hello. Sorry for late response but I think you can try to use [mongoid](https://github.com/mongodb/mongoid) with(or instead) hanami-models
