### ISSUE TITLE
Return type of private queries, incomplete documentation?

### ISSUE THREAD

**Issue by malin-as** [hanami/model#464]
Hi,

The [repository's guide](http://hanamirb.org/guides/1.1/repositories/overview/) states that all the queries should be private. However, the first example provided returns a `ROM::Repository::RelationProxy` object, instead of, say, an `Array` of `Book`s. I think this causes two problems:

1. This object contains a pending query, which might be executed way later, when rendering the web page
2. The internal Repository API is still exposed, which sorts of defeats the point of making the query private in the first place

Assuming that the documentation is incomplete, I noticed that in one example at the bottom of the [SQL Queries](http://hanamirb.org/guides/1.1/repositories/sql-queries/) page, the `to_a` method used returns the expected `Array` of `Book`s. So it seems that it should be used every time a query should return multiple results. But this method is not documented. Does it come from ROM? What would be the other available methods for transforming the query into something made of `Book`s? I only know of two others: `first` and `last`.

**Comment by jodosha** [comment]
@malin-as 
> However, the first example provided returns a ROM::Repository::RelationProxy
Which one, specifically?

> 1. This object contains a pending query, which might be executed way later, when rendering the web page

Why is this a problem? If you won't take advantage of the query laziness, you can materialize it immediately with `to_a` (inside the method implementation).

It returns that `RelationProxy` for reusability: you can pass around queries as scopes to other methods.

> 2. The internal Repository API is still exposed, which sorts of defeats the point of making the query private in the first place

With Ruby nothing is really "private" like in other languages. Even the SemVer conventions that we use are an indication for developers to **not** use method marked as _private_. The same thing apply for the methods inside a repository: you're warned to encapsulate queries into public methods.

---

> Does it come from ROM? What would be the other available methods for transforming the query into something made of Books?

Yes it's ROM. You can use `one` and `one!` as well. Where do you think we should document those cases?

**Comment by malin-as** [comment]
@jodosha 
My main consideration here is the "fail fast" approach. If my query is going to fail for some reason, I would like that to happen as early as possible, so typically when running it from the controller. If I want to write some code to handle the exceptions, I know I can do it in the controller. It is also going to spare some CPU cycles.

I would argue that query re-use should only happen from within the Repository, in which case the methods returning the `RelationProxy` should be `private` (I am aware that in Ruby, this is easy to circumvent), and another method would be needed to call them directly (and that method would materialize the query before returning to the controller).

Maybe your point is that materialising the query can happen either in the Repository code, or in the controller, in which case we are acutally agreeing for the most part. But I would disagree about letting the `RelationProxy` object make its way to the template engine and fail there.
