### ISSUE TITLE
Error with groub by / count ?

### ISSUE THREAD

**Issue by larssolem** [hanami/model#466]
Looks like there is an issue with the mapping of result from the sql query given by the example below.
The SQL query that is generated from the function is correct. But only the destination and result data becomes available in the returned Relation object. If i rename :count to a name that is a field in the table it gets mapped to the returned Relation object.

```ruby
   def errors_grouped(tag, from, to)
            outgoings.select(:destination, :result) { int::count(destination).as(:count) }
             .where(timestamp: from..to)
             .where { message_tag.ilike("tag:#{tag}%") }
             .group(:destination, :result)
             .order(:destination)
  end
```

returned object:
`#<Outgoing:0x00563f0c87f478 @attributes={ :destination=>"4798877015", :result=>1}>`

**Comment by jodosha** [comment]
@larssolem Can you please also share here an example of the generated SQL? Thanks.

**Comment by larssolem** [comment]
SELECT "destination", "result", COUNT("destination") AS "message_tag" FROM "outgoings" WHERE (("timestamp" >= '2017-10-01 00:00:00.000000+0000') AND ("timestamp" <= '2017-11-21 00:00:00.000000+0000') AND ("message_tag" ILIKE 'tag:seas-next%' ESCAPE '\'))

**Comment by jodosha** [comment]
@larssolem 
> But only the destination and result data becomes available in the returned Relation object.

I think this is the expected behavior. If you use `#select`, only the referenced columns are filled in the returning object. Am I missing something? What would you expect?

**Comment by larssolem** [comment]
The sql does generate a count column in adition too the columns. If i run the generated query directly on the SQL database I get: destination: xxxxxxxxxx, result: 1, count: 1
but the returned relation object only includes destination and result.

**Comment by kaikuchn** [comment]
Yeah that does not work, because you do not have an entity with a `count` attribute.
I think that's how ROM is supposed to work. I.e., you need to have an entity for your aggregate, say something like this:

```ruby
class ErrorGroups < Hanami::Entity
  attributes do
    attribute :destination, Types::String
    attribute :result, Types::String
    attribute :count, Types::Int
  end
end
```

**Comment by jodosha** [comment]
@larssolem Thanks to @kaikuchn now I understand the question. His suggestion should fix the problem.
