### ISSUE TITLE
Repository coerces string datetime inconsistently in daylight saving timezone

### ISSUE THREAD

**Issue by diawl** [hanami/model#469]
I created a new hanami project with latest version of Hanami(1.1)
`hanami new time_zone_experiments`

In this project, I did following things to set up experiments:

1, create a model with datetime field 
`hanami generate model model_with_datetime`

2, add `pg` to `gemfile`
```
#Gemfile
...
gem 'pg'
...
```

3, `bundle install`

4,  update the following files.
```
#environment.rb
...
  model do
    adapter :sql, 'postgres://localhost/time_zone_experiment_development'

    ##
    # Migrations
    #
    migrations 'db/migrations'
    schema     'db/schema.sql'
  end
...
```
```
#database.yml
default: &default
 adapter: postgresql
 timeout: 5000
 pool: 5
```
```
#entity
class ModelWithDatetime < Hanami::Entity
  attributes do
    attribute :id,              Types::Int
    attribute :start_at,        Types::DateTime
    attribute :end_at,          Types::DateTime
  end
end
```
```
#repository
class ModelWithDatetimeRepository < Hanami::Repository
  self.relation = :model_with_datetimes

  schema do
    attribute :id,              Hanami::Model::Sql::Types::Int
    attribute :start_at,        Hanami::Model::Sql::Types::DateTime
    attribute :end_at,          Hanami::Model::Sql::Types::DateTime

    primary_key :id
  end
end
```
```
#migration
Hanami::Model.migration do
  change do
    create_table :model_with_datetimes do
      primary_key :id
      column :start_at, DateTime
      column :end_at, DateTime
    end
  end
end
```
5, `hanami db prepare`
6, then it should be ready to go
```
▶ hanami c
2.4.2 :001 > repo=ModelWithDatetimeRepository.new
 => #<ModelWithDatetimeRepository relations=[:model_with_datetimes]>
2.4.2 :002 > repo.create(start_at: '2017-10-01 03:00:00', end_at: '2017-10-01 03:30:00')
[time_zone_experiments] [INFO] [2017-11-28 11:33:52 +1100] (0.000489s) SELECT "id", "start_at", "end_at" FROM "model_with_datetimes" LIMIT 1
[time_zone_experiments] [INFO] [2017-11-28 11:33:52 +1100] (0.006495s) INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 03:00:00', '2017-10-01 03:30:00') RETURNING *
 => #<ModelWithDatetime:0x00007fb3d76d3d68 @attributes={:id=>1, :start_at=>2017-10-01 03:00:00 UTC, :end_at=>2017-10-01 03:30:00 UTC}>
2.4.2 :003 > repo.create(start_at: '2017-10-01 02:00:00', end_at: '2017-10-01 02:30:00')
[time_zone_experiments] [INFO] [2017-11-28 11:33:59 +1100] (0.006312s) INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 02:00:00', '2017-10-01 02:30:00') RETURNING *
 => #<ModelWithDatetime:0x00007fb3d76c08d0 @attributes={:id=>2, :start_at=>2017-10-01 03:00:00 UTC, :end_at=>2017-10-01 03:30:00 UTC}>
2.4.2 :004 > repo.create(start_at: '2017-10-01 02:00:00+1000', end_at: '2017-10-01 02:30:00+1000')
[time_zone_experiments] [INFO] [2017-11-28 11:34:18 +1100] (0.006176s) INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 02:00:00+1000', '2017-10-01 02:30:00+1000') RETURNING *
 => #<ModelWithDatetime:0x00007fb3d76a8960 @attributes={:id=>3, :start_at=>2017-10-01 03:00:00 UTC, :end_at=>2017-10-01 03:30:00 UTC}>
2.4.2 :005 > repo.create(start_at: '2017-10-01 02:00:00+0000', end_at: '2017-10-01 02:30:00+0000')
[time_zone_experiments] [INFO] [2017-11-28 11:34:28 +1100] (0.002353s) INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 02:00:00+0000', '2017-10-01 02:30:00+0000') RETURNING *
 => #<ModelWithDatetime:0x00007fb3d76909f0 @attributes={:id=>4, :start_at=>2017-10-01 03:00:00 UTC, :end_at=>2017-10-01 03:30:00 UTC}>
```
As you can see, `2017-10-01 02:00:00` and `2017-10-01 03:00:00` got converted into same value by repository. And putting timezone info in the string doesn't change the outcome, `2017-10-01 02:00:00+0000` is converted to `2017-10-01 03:00:00 UTC` anyway.

I did a bit of digging, seems like it has something to do with my computer's timezone setting. My laptop's timezone is in Melbourne(MacOS: System Preferences -> Date & Time). `2017-10-01 02:00:00` is a daylight saving switching point so we lose one hour between 2am to 3am, which means time series around that point are like this: `01:58+1000, 01:59+1000, 03:00+1100, 03:01+1100`, so times start with `02` at that day in Melbourne do not exist. What makes me confused is repository on one hand is ignoring timezone info in my input, but on the other hand is validating and coercing the input with system(my laptop) timezone.

One thing worth mentioning:
The example above is using `postgres`. When I was using `sqlite` by default, it only had part of the problem. With `sqlite`, it still parses `2017-10-01 02:00:00` to `2017-10-01 03:00:00 UTC`, but input with timezone info is processed correctly. `2017-10-01 02:00:00+1000` will be converted to `2017-09-30 16:00:00 UTC`.

**Comment by diawl** [comment]
@kaikuchn @jodosha here is the timezone issue we talked about in gitter.

**Comment by kaikuchn** [comment]
`DateTime` creates a timestamp without time zone field in postgres. As the [docs](https://www.postgresql.org/docs/current/static/datatype-datetime.html#DATATYPE-DATETIME-INPUT) say "In a literal that has been determined to be timestamp without time zone, PostgreSQL will silently ignore any time zone indication."

It is therefore no surprise that your offset is ignored. What I do not understand yet, is why `'2017-10-01 02:00:00'` is returned as `2017-10-01 03:00:00 UTC`

**Comment by kaikuchn** [comment]
Just to check, what does `SHOW timezone;` say in psql? And when you go into the psql shell and run `INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 02:00:00', '2017-10-01 02:30:00') RETURNING *` what does that return?

**Comment by diawl** [comment]
`SHOW timezone;` gives me this
```
psql 'postgres://localhost/time_zone_experiment_development'
psql (9.6.1, server 9.6.5)
Type "help" for help.

time_zone_experiment_development=# SHOW timezone;
      TimeZone
--------------------
 Australia/Victoria
(1 row)
```

`INSERT` gives me this
```
time_zone_experiment_development=# INSERT INTO "model_with_datetimes" ("start_at", "end_at") VALUES ('2017-10-01 02:00:00', '2017-10-01 02:30:00') RETURNING *;
 id |      start_at       |       end_at
----+---------------------+---------------------
  5 | 2017-10-01 02:00:00 | 2017-10-01 02:30:00
(1 row)

INSERT 0 1
```
and here is the description of table
```
time_zone_experiment_development=# \d+ model_with_datetimes;
                                                        Table "public.model_with_datetimes"
  Column  |            Type             |                             Modifiers                             | Storage | Stats target | Description
----------+-----------------------------+-------------------------------------------------------------------+---------+--------------+-------------
 id       | integer                     | not null default nextval('model_with_datetimes_id_seq'::regclass) | plain   |              |
 start_at | timestamp without time zone |                                                                   | plain   |              |
 end_at   | timestamp without time zone |                                                                   | plain   |              |
Indexes:
    "model_with_datetimes_pkey" PRIMARY KEY, btree (id)
```

**Comment by kaikuchn** [comment]
Alright, so now we know that there is a bug somewhere in handling the values returned from the insert statement. Probably the time without timezone information is wrongly assumed to be in local time, the period is not found and thus gracefully corrected to the nearest existing period (i.e., DST).

**Comment by kaikuchn** [comment]
@jodosha this is most likely a downstream bug, though I cannot tell where exactly.
