### ISSUE TITLE
Entity#to_h is not recursive

### ISSUE THREAD

**Issue by apohllo** [hanami/model#470]
The implementation of Entity#to_h is not recursive. i.e. doesn't convert to hash entities that are associated with the entity being converted. Would you consider making it recursive?

**Comment by cllns** [comment]
What's the use-case for this? 

Would the representer pattern be helpful? Something like [`roar`](https://github.com/trailblazer/roar).

We'd need to deal with circular dependencies somehow, if we did this.

**Comment by apohllo** [comment]
Well, the primary use-case for me is a JSON API. I compared the output of `Dry::Struct#to_h` (which I believe is much similar to `Hanami::Entity`) and it does a recursive conversion. I considered the replacement of `Hanami::Entity` with `Dry::Struct` but it's not as straightforward as it seems.

To give you more context - I'm experimenting with `Transproc` as the primary library for building the JSON output and the most straightforward approach is to convert the entity to Hash, and then apply some other conversions. I am not sure at the moment that this is the best approach.
Anyway it is still easy do the conversion on the `Transproc` side, so this was more like a question - not a bug report or a feature request ;-)

**Comment by mereghost** [comment]
@apohllo I'm pretty sure we had some troubles with this before but could not find the exact issue. =/

That being said, you can use `Hanami::Utils::Hash.deep_serialize` to do what you need.

**Comment by mereghost** [comment]
As the opener seems to have solved his troubles, I'm closing this.

**Comment by apohllo** [comment]
Yes, thanks, that's fine. I started using Transproc as a primary means for converting the data, which suites my needs perfectly. So I think there's no need to repeat the same functionality in Hanami.

**Comment by flash-gordon** [comment]
transproc ftw!
