### ISSUE TITLE
How to map to a custom postgres schema?

### ISSUE THREAD

**Issue by AlexVKO** [hanami/model#472]
Hello Guys,
I'm using PostgreSQL and I'm having a hard time to make Hanami search for tables inside a custom schema instead of the public... 

How can I do that?

**Comment by mereghost** [comment]
Hey there, @AlexVKO !

Well, if I'm not mistaken `rom-rb` does not still support multiple schemas, and we use it under the hood. That being said, postgres has a `search_path` setting that can be passed onver dureing connection (`postgres://localhost/rom_sql?search_path=schema1,schema2`).

The original issue (and this solution) can be found over rom-rb/rom-sql#163 .

**Comment by AlfonsoUceda** [comment]
Hi @AlexVKO sorry fo the trouble, did @mereghost's suggestion work fine?

**Comment by AlexVKO** [comment]
Hello, 

Sorry for the delay.

The search patch was not doable for us, due de fact we have tables with the same name in different schemas, some examples:
```
- dropshipper.users
- supplier.users

- store.orders
- supplier.orders

and many more...
```

Unfortunately we moved from Hanami for this and other reasons, we we're spending a lot of time for doing things that should be faster, and you know, in a startup real world we need to deliver things fast to hear feedback and etc, it was not ideal.

I'm not saying that Hanami is bad(I do like Hanami alot), but it was not been the suitable chose for the moment and for the team.

I'm closing this. Thank you guys.

**Comment by AlfonsoUceda** [comment]
@AlexVKO thanks for your feedback because it is valuable for us. Can you tell us more reasons about that decision? we need to improve and that would be awesome.
