### ISSUE TITLE
Apply the Strict  to only a part.

### ISSUE THREAD

**Issue by ippachi** [hanami/model#488]
On hanami-1.2.0, I ran a below code

```ruby
require 'hanami-model'

class User < Hanami::Entity
  attributes do
    attribute :name, Types::Strict::String
    attribute :email,  Types::String
  end
end

User.new # => #<User:0x0000563a7ea8f2a0 @attributes={}>
```
and not raises a error.
I expect `ArgumentError: name  is missing in Hash input`.

and after saw the `hanami/entity/schema.rb: 111`, I tried the below code.

```ruby
require 'dry-types'
Dry::Types['coercible.hash'].schema({name: Types::Strict::String}).call({}) # => {}
```
and not raises a error.

It seems that `Dry::Types::Hash` doesn't support `Types::Strict`
I have no idea that this is bug or a specification.

I have a way for solve this bug.
but if apply that, we will not be able to write this code

```ruby
class User < Hanami::Entity
  attributes :strict do
    attribute :name, Types::String
    attribute :email,  Types::String
  end
end
```

**Comment by jodosha** [comment]
@ippachi Yes, you can choose to apply strict policy only for a few attributes. That means the last snippet should work. If it doesn't, it's a bug.
