### ISSUE TITLE
Type of Postgres json/b columns is not correctly inferred

### ISSUE THREAD

**Issue by checkbutton** [hanami/model#497]
While the regular repository `update` method correctly infers the json/b column type, this here does not:
```ruby
class BirdRepository < Hanami::Repository
  def update_starling(id, meta)
    birds.where(type: 'starling').where(id: id).update(meta: meta)
  end
end
```
`meta` is a Ruby Hash. It works with `.update(meta: Sequel.pg_jsonb(meta))`, yet this breaks the repository's storage independency.

**Comment by mereghost** [comment]
Hi @checkbutton , thanks for the report.
I'll see if there's anything we can do to make the user experience a bit better (although I think it's more a problem outside of our reach - Sequel in this case). 

OTOH, one might argue that using jsonb already makes you DB dependent as the field exists only on PG anyway.

**Comment by checkbutton** [comment]
@mereghost Agree, jsonb is very specific here. Can I use a type "Hash" on the schema, which then infers a type according to DB driver?

**Comment by katafrakt** [comment]
@checkbutton I think it would still be ambiguous. In PostgreSQL for example it can be jsonb, json or even hstore if the hash is one-level deep.
