### ISSUE TITLE
Update to ROM 4.0?

### ISSUE THREAD

**Issue by nbfritz** [hanami/model#499]
I wanted to incorporate ROM Factory into a project but ran into a number of version conflicts that locked me to version 0.4 rather than the newest 0.6 of the library. That led me to notice that ROM is currently version locked to the 3.3 line which was replaced by version 4.0 almost a year ago (from what I'm reading...I'm new to Hanami and ROM). 

Is there an initiative to update the dependencies of Hanami::Model or is this version lock an intention decision until a future version of Hanami is released?

**Comment by davydovanton** [comment]
hey, we want to update rom to 4.0 version in next release. Now, to fix your problem try to use this gem:

**Comment by nbfritz** [comment]
Thank you. That's good to know.

I had looked at Fabrication as an alternative, but shifted to ROM Factory thinking it would play more nicely with ROM. I'll give hanami-fabrication another try. It does appear that ROM Factory is still a bit early in its development anyway...

**Comment by jdickey** [comment]
@nbfritz Not sure why I only saw this notification now (I'm watching the repo), but I've been using `hanami-fabrication` for months now and it's been sweet. Ping me if I can help with anything.
