### ISSUE TITLE
Optimistic Locking

### ISSUE THREAD

**Issue by mbriggs** [hanami/model#510]
Is there a way to do something similar to this with hanami? https://api.rubyonrails.org/classes/ActiveRecord/Locking/Optimistic.html

Essentially, "UPDATE ... WHERE version = <version_from_model>" with an exception if it fails. I saw a mention of Custom Commands in the docs, but it doesn't really go into detail on how to use them

**Comment by mbriggs** [comment]
asking in gitter

**Comment by kaikuchn** [comment]
For posteriority, according to jodosha:

> We don't support that. Maybe this helps: https://blog.2ndquadrant.com/postgresql-anti-patterns-read-modify-write-cycles/ (Jump to the Optimistic Locking section).

[Source](https://gitter.im/hanami/chat?at=5c0fc47080986419d57474f8)
