### ISSUE TITLE
Repository #find_or_create_by

### ISSUE THREAD

**Issue by matheusazzi** [hanami/model#516]
Is there any interest in having something similar to [AR#find_or_create_by](https://apidock.com/rails/v4.0.2/ActiveRecord/Relation/find_or_create_by) as a `Hanami::Repository` core method?

```ruby
repository = UserRepository.new
repository.find_or_create_by(name: 'Luca')

user = User.new(name: 'Luca')
repository.find_or_create_by(user)
```

**Comment by jodosha** [comment]
@matheusazzi Hi and thanks for this proposal.

The main design principle behind repositories is: hide low level details.
By exposing `name` as a keyword argument goes against this principle.

---

Why did you closed the ticket right after you opened it?

**Comment by matheusazzi** [comment]
Hey @jodosha, I should have been clearer on why I closed it, but it was what you said. 
I figured out it doesn't make much sense as a Repository responsibility and I think if having a logic like that it should be done in another place.
