### ISSUE TITLE
Private method 'Array' in hanami entity

### ISSUE THREAD

**Issue by ahmeddwaheed** [hanami/model#519]
while type Array is defined in hanami entity attributes when trying to use it, it throws an error of a private method 'Array'  called for Hanami::Entity::Types:Module

```ruby
require 'hanami/model'

class Foo < Hanami::Entity
  attributes do
    attribute :users, Types::Array(User)
  end
end
```

**Comment by flash-gordon** [comment]
No, it's not defined, this method is from `Kernel`, it's overridden in later versions of dry-types, seems like the version used by hanami-model doesn't have it yet. Use `Types::Array.of(User)` or `Types::Array.member(User)`. One of the two should work.

**Comment by ahmeddwaheed** [comment]
@flash-gordon thank you it worked :+1:
