### ISSUE TITLE
db prepare raises Postgres createdb error

### ISSUE THREAD

**Issue by hedselu** [hanami/model#595]
I encountered error from postgres version 13 in `createdb` command while trying to run `hanami db prepare` on clean app.

error trace shows problem in `path/hanami/model/migrator/postgres_adapter.rb:103`. 

Checking `command_with_credentials` method I see there's password option applied for database command:
```ruby
result << "--password=#{password}" unless Utils::Blank.blank?(password)
```
I thought it might be the case, that postgres version 13 dropped support of passing password value to this option, but it looks like there was never such possibility.

https://www.postgresql.org/docs/9.1/app-createdb.html

Please, correct me if I am wrong.

**Comment by hedselu** [comment]
Ok, after further investigations the problem lays in master branch which has a possible bug. I was basing on master as it was recommended in this issue https://github.com/hanami/model/issues/570 for ruby 2.7. I think it will be better to downgrade ruby to 2.3 instead :thinking:

**Comment by cllns** [comment]
I've tried to reproduce this in a number of ways but I haven't been able to. It'd be super helpful if you can provide a short list of commands/instructions that reproduce this issue, and/or if you can create a GitHub repo and link to it here so I can look into this more. Thanks!

**Comment by hedselu** [comment]
I've added repository right here: https://github.com/hedselu/hanami-db-error

I am unsure how did you set up db connection when trying to reproduce (thanks for trying and my apologies for not including this info), but have a look at `.env.development` file, where database credentials are included in URL. The problem might be only when authenticating with password.

**Comment by dudo** [comment]
I ran into the same issue on `master`. Monkey patching the adapter to remove the password fixed it. I'm on postgres 11.11. Set the db back to 11.10, and 11.9, with the same results, so it definitely doesn't appear to be a database issue.

I printed out `command_with_credentials` and it definitely includes `--password`, which isn't supported. 

Reverting to `1.3.2` resolves it as well, so there seems to be something in `master`

**Comment by hedselu** [comment]
@adam12 I see a merged PR related to this issue. Thanks for taking care of this! Do you think this issue is closable now?

**Comment by adam12** [comment]
@hedselu Not yet, but thanks for checking.

I think there is still an underlying issue that `--password=` isn't a valid argument to Postgres CLI tools. I'd like to fix it, but the mentioned PR is to get tests working reliably first.

**Comment by dudo** [comment]
That seems to be only CI related... code change doesn't address our issue at all. If anything, that PR just further hides this bug.

**Comment by adam12** [comment]
> that PR just further hides this bug

Possibly, tho I did highlight it in the opening of the PR and would like to resolve it without manually forcing `PGPASSWORD` in the CI config.

Are you interested in submitting a PR for this issue?

**Comment by wenderjean** [comment]
If there is no one else dealing with this issue I can do that @adam12

**Comment by adam12** [comment]
> If there is no one else dealing with this issue I can do that

Thanks for the offer but I did end up with a [fix in another branch](https://github.com/hanami/model/tree/ad/pg-env-variables), but I need to debug the CI failing again.

**Comment by adam12** [comment]
I've opened https://github.com/hanami/model/pull/622 to fix this. Is anybody willing to give it a try?

**Comment by wenderjean** [comment]
I'll give it a try later on today :)

**Comment by adam12** [comment]
> I'll give it a try later on today :)

Did you ever get a chance to try out my fix? No worries if you didn't.

**Comment by wenderjean** [comment]
I did @adam12, sorry for the delay.
I used those versions below to test, both of them I got the error before and I could create/migrate successfully on your branch.

- [x] Postgresql 11
- [x] Postgresql 12
- [x] Postgresql 13
